### ISSUE TITLE
Document the required component configuration structure

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#41]
All the components need a configuration in order to be able to be used by the Lumina page builder.

Create the required documentation for this configuration.

Take into consideraction the configuration already done, plus the one needed by storybook, since we may need to integrate it in the future.

**Comment by AdrianaAC** [comment]
Basic configuration (general) described. 
Listing items is giving errors with storybook

**Comment by AdrianaAC** [comment]
General configuration and individual configuration splited.
Use same components as examples in both - image and button?

**Comment by AdrianaAC** [comment]
change structure -> general configuration + component configuration ok ?

**Comment by AdrianaAC** [comment]
Final structure.
Added more examples.
editor object as default ?

**Comment by AdrianaAC** [comment]
Added examples, with ts configuration.
default values dor editor {}?
