### ISSUE TITLE
create documentation on how to add new components

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#42]
Create the needed documation explaining what is needed to add new custom component to the application.

**Comment by AdrianaAC** [comment]
Added example, to test creating component.
Basic strecture of document added,  with basic sections

**Comment by AdrianaAC** [comment]
Examples and linking - external files linking working.
 Internal linking not jumping to sections

**Comment by AdrianaAC** [comment]
Bug detected:
Linking internal sections is not working. When clicking on the link, the url chages but the pages does not jump to the section. The page does not reflect the current url.

To replay this bug:
-> Open docs Add new component and check its url
-> On Guide, step 3, click on linked General Configuration. Check url, it changes but the rendered page does not.
-> Refresh page, click on section General Configuration. Check url (we can see its the same as before)

**Comment by AdrianaAC** [comment]
To do:
Create and configuration needs more text.

Completed:
Reviewed import tables, avoid using the requested phrasing.
Reviewed lumina configuration section.
Added more info to helpers section.
Added TComponentConfig and TConfig objects to examples.
