### ISSUE TITLE
Close the modal when clicking outside

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#44]
![Image](https://github.com/user-attachments/assets/78e31986-cdff-47ab-8aa9-2f8a2cc8ed43)

When the user clicks outside the modal, it should close the modal automatically with a “cancel” action.

**Comment by JWebCoder** [comment]
@AdrianaAC , any news regarding this?

**Comment by AdrianaAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Close the modal when clicking outside](https://trello.com/c/GqPO8LLF/76-close-the-modal-when-clicking-outside)
