### ISSUE TITLE
Fix edit icon on LinkBox component

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#46]
![Image](https://github.com/user-attachments/assets/317c3d03-d2b9-48ea-b7f3-e7ab0a79c801)

When the edit icon is clicked, on the LinkBox component, the user is also being redirected to the href defined.

This should not happen, and it should only show the modal.

**Comment by bmirra01** [comment]
After some digging, it seems that the Add, Edit and Delete handlers for the Modals were missing a preventDefault() to avoid these kind of secondary and undesirable actions to happen.
