### ISSUE TITLE
Implement the Visible toggle

### ISSUE THREAD

**Issue by AdrianaAC** [Funfunz/lumina-next#52]
![Image](https://github.com/user-attachments/assets/4389c970-cdcc-4b16-be72-ec5327d19b68)

On click it should hide/show the component on the rendered page.

Use the app context to share a property responsible for this.

**Comment by AdrianaAC** [comment]
Component now hiding/showing from renderer page.
Icon (state?) not changing.

**Comment by JWebCoder** [comment]
I've fixed the icon change
I've also added added disable to the arrow items, they still need design that will be done on ticket

**Comment by AdrianaAC** [comment]
Clean and final fixes in place.
Log's from arrow items were kept.

**Comment by JWebCoder** [comment]
Why is this still in review? Any news regarding this? @AdrianaAC  @antonio-rodrigues  @Felix-by-merkle
