### ISSUE TITLE
Editor route

### ISSUE THREAD

**Issue by bmirra01** [Funfunz/lumina-next#57]
Editor mode should be toggled by a path ending in /editor

Going to https://example.com/editor should open the https://example.com page in editor mode.

**Comment by bmirra01** [comment]
Added the package to devDependancies "react-router-dom"
After implementation locally was working fine, but on Vercel when changing to /editor it returned a 404.. so after a lot of search it seems that we need to add a file "vercel.json" to bypass any other routes from vercel to our own, and after that it worked on Vercel. Not sure if in the future this will be needed (after merging to master for example). 
Waiting for merge at this point.

**Comment by JWebCoder** [comment]
Reopen issue.
Routing needs to be on the Demo App and not the Lumina core.
