### ISSUE TITLE
Add Lumina logo to sidebar as in Figma

### ISSUE THREAD

**Issue by Felix-by-merkle** [Funfunz/lumina-next#59]
Check [Lumina – Figma](https://www.figma.com/design/vLU4BPbeYY5Rt2TKHIMxmr/Lumina?node-id=18-18740&m=dev) and extract and add the Lumina Icon to the sidebar

**Comment by bmirra01** [comment]
It seems that adding the logo is not that simple, and after spending a whole morning and some hours in the afternoon, and giving that this is not a priority for now, this will be set on hold
