### ISSUE TITLE
Reset the applied filter in the component tree

### ISSUE THREAD

**Issue by antonio-rodrigues** [Funfunz/lumina-next#64]
After adding a keyword to search & filter the component tree, the user needs to clear the input box and hit "Search" again to reset the filter and be able to see all components in the tree.

There should be an option to reset the search/filtering.
Please, align with the designer to provide such option: it could be a new icon next to the "filter" one, or something similar.

![Screenshot 2024-08-21 at 12 12 55](https://github.com/user-attachments/assets/1a420eb8-e217-4fd7-8754-baab730d8aa5)

**Comment by antonio-rodrigues** [comment]
Some suggestions:
![Screenshot 2024-08-21 at 12 20 00](https://github.com/user-attachments/assets/74a192e6-933a-44f5-a63c-34fe91cda9d4)

![Screenshot 2024-08-21 at 12 26 10](https://github.com/user-attachments/assets/5f8702e9-1575-4ddb-a570-03e7f888749f)

**Comment by Felix-by-merkle** [comment]
Another way to reset it, would be to use typing to search, with a debounce, and if the input is empty reset the search

**Comment by bmirra01** [comment]
This is already implemented with the new forms, this can be closed.
