### ISSUE TITLE
Change Form and form Elements to React Hook Form

### ISSUE THREAD

**Issue by antonio-rodrigues** [Funfunz/lumina-next#67]
The current forms library is a bit overkill and has a steep learning curve.

Switch to the lighter React Hook Form.
Please, keep in mind any dependencies with other PRs/developers.
Check with others before starting to touch a component.

Strategy - multiple PR's

PR #.1
- Implement it separately, meaning that you recreate the same components but under a different name/domain. That way, the new ones won't affect immediately the existing implementation;

PR #.2
- Align with other developers - can they hold on a few hours? do not touch anything related with forms (html/behaviour), or at least not the same component
- Replace the "old" forms and components with the new ones. Make sure the logic and features are kept;
- The above can be a joint effort: after merging the PR#1 all developers can revisit their work and replace the old with the new ones.

#### Reference / samples

https://claritydev.net/blog/abstract-react-form-fields-with-field-component
https://claritydev.net/blog/form-validation-react-hook-form
https://claritydev.net/blog/abstract-react-form-fields-with-field-component
 
source code example:
https://github.com/Clarity-89/react-hook-form-example

**Comment by bmirra01** [comment]
Input and TextArea are basically done (component-wise), missing the implementation of React Hook Form's Library.

Checkbox and RadioButton are In Progress.

Slider and Switch will stay to the end.

**Comment by bmirra01** [comment]
First PR is ready for review.

On the 2nd PR will be done the following:

- Storybook update
- Remove react-form-component completely from the project
- Update any component that uses form components

**Comment by bmirra01** [comment]
Worked on the comments that were left (done):
- Fixed the slider 
- Moved the logic on the input into a custom hook to be called when needed
- Added 2 new helper components (help and label) to replace the common code across the Form components

I just have left to be done the RHF implementation, which will be done on Input component for validation test.

**Comment by bmirra01** [comment]
There was a bug with the prop 'name', which for some reason RHF was not validating the input fields correctly and not even submitting. I suspect that the combo of htmlFor={name} and the misuse of this prop could be the leading issue to it, so for now I've removed it from all form components as this was just being used to refer a label to the input, and is not needed at least for now. Everything is working as expect @JWebCoder  and @antonio-rodrigues , you can check the PR when you got some time.
