### ISSUE TITLE
Create the CRUD actions for the pages

### ISSUE THREAD

**Issue by bmirra01** [Funfunz/lumina-next#80]
Create the CRUD actions to create, read, update, and delete pages.
It should be possible for the user to manage pages on the Lumina editor.

Follow the same layout we used for the component list but without the nesting (to be added on a later version)

It should be possible to CRUD the pages in a very simple way.

Future versions will also include nested pages.

## Acceptance criteria

- 3 new actions are available on the context of the application: createPage, editPage and deletePage.

### createPage

creates a new page structure and adds it to the current application context
It should receive the following data object:
- friendlyName: friendly name of the page
- descirption: description of the page
- urlParams: an array of strings in the correct order to build the required URL path

A unique page ID needs to be generated and added to the page data object. This unique ID will be used by the edit to be able to edit all fields and still be able to target the correct page.

**Final URL structure:**

This final structure needs to be created by the addPage and editPage actions.

The final URL structure needs to have the following structure:

/urlParams[0]/:urlParams[1]/...

Each URLParameters will be in the form of:
**/:urlParameter**

### edit page

Same as create page, but will edit an already existing page based on the id of the page.
The ID of the page cannot be edited, and this action will never generate a new ID.

### delete page

Gets the page ID and deletes the page from the application context

**Comment by bmirra01** [comment]
@JWebCoder / @antonio-rodrigues, we need to make a decision before proceeding, in relation to the componentes on lumina-core/packages/src/components/action-buttons, which currently are the buttons in every tab of our app, and are the ones activating the Modals to CRUD but only for components. In my mind, it would make sense to extend these buttons to also work with the pages, if not, would have to create another set of buttons only for pages. Let me know your thoughts on this please. Thanks

**Comment by bmirra01** [comment]
AddPage is working:

![Image](https://github.com/user-attachments/assets/c0909940-613c-44bd-8bf5-8a4fb462a767)

Delete is working:


![Image](https://github.com/user-attachments/assets/c1004cba-e28f-40cd-96d1-808c62b3c870)

Still working on the Edit, which is not working yet

**Comment by JWebCoder** [comment]
I've removed the pageName from the data needed, using the urlParams instead

**Comment by JWebCoder** [comment]
I've done some code restructure and data structure changes to have better management of the entire page logic.

**Comment by JWebCoder** [comment]
pull request created and waiting for review
