### ISSUE TITLE
Create the required components for the demo page

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#85]
Create a list and estimations of all the required components to build the demo website

We will integrate [Chakra UI](https://v2.chakra-ui.com/) components as a component library.

Final version is still **on hold**

# On Hold:

### Waiting for:

https://github.com/orgs/Funfunz/projects/3/views/1?pane=issue&itemId=73753140

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by JWebCoder** [comment]
Moved back to TODO in favor of other more urgent issues.

**Comment by JWebCoder** [comment]
pull request created.

I've added some components to the vite-react app to be able to build more complex pages
Added a new page for the route /product/:productId used to create the product page
Improved Material UI theme
Shared context between components
Improved routing
Added application stylesheet
Updated font to use Roboto
