### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by JWebCoder** [Funfunz/lumina-next#87]
The editor should be behind a log in system.

Create a login page that will be rendered in case the user is not logged in.

Make the user logged in by either creating a cookie or adding some data to the session storage to fake a real user authentication.

This needs to be connected to a real backend in the future.

## Acceptance criteria:
- Login page created with:
  - email and password fields
  - button to login
  - link to recover password
  - link to create account
- Recover password page created with:
  - email field
  - button to recover password
  - button to go back
- Create account page created with:
  - email, password and repeat password fields
  - button to create account
  - button to go back

**Comment by AdrianaAC** [comment]
Login page as figma (except links).

To do:
Links to other pages - no design yet, using login page design
Re-arrange login system
Re-arrange login to be in lumina package

**Comment by AdrianaAC** [comment]
When login is successfull, user is redirected to /editor.

To do:
Editor should be "locked" behind login

**Comment by AdrianaAC** [comment]
Login is now on Lumina core, not examples.
Editor is locked behind loggin - ok ?

To do:
Review styles, not being applied

**Comment by AdrianaAC** [comment]
Styles reviewed and updated

**Comment by AdrianaAC** [comment]
Login system now only active if editor mode is active
