### ISSUE TITLE
Create the page list component

### ISSUE THREAD

**Issue by AdrianaAC** [Funfunz/lumina-next#94]
Follow the same layout we used for the component list but without the nesting (to be added on a later version)

Future versions will also include nested pages.

## Acceptance criteria 

- user can see the list of pages created
- each list item has an edit and delete button in front of it
- all data should come from the context and completely dynamic

**Comment by JWebCoder** [comment]
Started initial implementation, the treeview is already visible but it's missing the buttons to CRUD
